[aosp/LA.UM.7.1.r1] Add option to set build_directory manually
sonyxperiadev/kernel-sony-msm-4.14-common pull request #13
Opened 2020-11-03 17:56 UTC by Thaodan

2020-11-03 18:03 UTC, MarijnS95 commented
It's pretty common (make, cmake, ninja, tar, unzip etc) to use `-C` to specify an output directory (usually interpreted as "change to this directory before running).

2020-11-03 18:05 UTC, Thaodan commented
No -C is to switch to that directory: "Change to directory dir before reading the makefiles or doing anything else"

2020-11-12 10:55 UTC, sledges commented
And when you switch to an empty directory, the build should then fail, so using `-C` doesn't really fit here.

May I propose a compromise, `make O=DIR` is what we're trying to achieve here, so maybe an `-O`? :)

PS: tested the PR, works as expected!

2020-11-12 18:05 UTC, Thaodan commented
Sounds good to me,  adjusted to that idea.

2020-11-13 13:57 UTC, sledges requested changes
May I suggest to squash both commit as they are mutually inclusive?

2020-11-13 13:57 UTC, sledges commented on build_shared_vars.sh
>  }
^ usage would need a new parameter too

2020-11-13 13:59 UTC, sledges requested changes

2020-11-13 13:59 UTC, sledges commented on build_shared_vars.sh
> +arguments=khd:D:
This also needs changing to O.

2020-11-13 14:41 UTC, Thaodan commented
Done, done and done

2020-11-13 15:28 UTC, merged